apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: svc-hello

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

images:
- name: ghcr.io/afontan/svc-hello
  newName: ghcr.io/afontan/svc-hello
  newTag: 088e13c
